# Generated by Django 3.1.1 on 2020-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200905_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
